In [13]:
import pandas as pd
from pathlib import Path

BASE = Path("../data/raw")

# better table display
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1200)
pd.set_option("display.max_colwidth", 100)

# warning fix (mixed types)
import warnings
warnings.filterwarnings("ignore")

In [14]:
df_raw = pd.read_csv(BASE / "core/AVONET_Raw_Data.csv", encoding="latin1")

print("Shape:", df_raw.shape , "\n")
print("Columns:", list(df_raw.columns) , "\n")
df_raw.head()

Shape: (90371, 204)

Columns: ['Avibase.ID', 'Species1_BirdLife', 'Species2_eBird', 'eBird.species.group', 'Species3_BirdTree', 'Data.type', 'Source', 'Specimen.number', 'Sex', 'Age', 'Locality', 'Country_WRI', 'Country', 'Beak.Length_Culmen', 'Beak.Length_Nares', 'Beak.Width', 'Beak.Depth', 'Tarsus.Length', 'Wing.Length', 'Kipps.Distance', 'Secondary1', 'Hand-wing.Index', 'Tail.Length', 'Measurer', 'Protocol', 'Publication', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129', 'Unnamed: 130', 'Unnamed: 131', 'Unnamed: 132', 'Unnamed: 133', 'Unnamed: 134', 'Unnamed: 135', 'Unnamed: 136', 'Unnamed: 137', 'Unnamed: 138', 'Unnamed: 139', 'Unnamed: 140', 'Unnamed: 141', 'Unnamed: 142', 'Unnamed: 143', 'Unnamed: 144', 'Unnamed: 145', 'Unnamed: 146', 'Unnamed: 147', 'Unnamed: 148', 'Unnamed: 149', 'Unnamed: 150', 'Unnamed: 151', 'Unnamed: 152', 'Unnamed: 153', 'Unnamed: 154', 'Unnamed: 155', 'Unnamed: 156', 'Unnamed: 157', 'Unnamed: 158', 'Unnamed: 159', 'Unnamed: 160', 'Unnamed: 161', 'Unnamed: 162', 'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165', 'Unnamed: 166', 'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169', 'Unnamed: 170', 'Unnamed: 171', 'Unnamed: 172', 'Unnamed: 173', 'Unnamed: 174', 'Unnamed: 175', 'Unnamed: 176', 'Unnamed: 177', 'Unnamed: 178', 'Unnamed: 179', 'Unnamed: 180', 'Unnamed: 181', 'Unnamed: 182', 'Unnamed: 183', 'Unnamed: 184', 'Unnamed: 185', 'Unnamed: 186', 'Unnamed: 187', 'Unnamed: 188', 'Unnamed: 189', 'Unnamed: 190', 'Unnamed: 191', 'Unnamed: 192', 'Unnamed: 193', 'Unnamed: 194', 'Unnamed: 195', 'Unnamed: 196', 'Unnamed: 197', 'Unnamed: 198', 'Unnamed: 199', 'Unnamed: 200', 'Unnamed: 201', 'Unnamed: 202', 'Unnamed: 203']

,Avibase.ID,Species1_BirdLife,Species2_eBird,eBird.species.group,Species3_BirdTree,Data.type,Source,Specimen.number,Sex,Age,Locality,Country_WRI,Country,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-wing.Index,Tail.Length,Measurer,Protocol,Publication,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Unnamed: 153,Unnamed: 154,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unnamed: 159,Unnamed: 160,Unnamed: 161,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178,Unnamed: 179,Unnamed: 180,Unnamed: 181,Unnamed: 182,Unnamed: 183,Unnamed: 184,Unnamed: 185,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200,Unnamed: 201,Unnamed: 202,Unnamed: 203
0,AVIBASE-B3F5E5E2,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,1.0,NHMUK,11.4.1890,F,0.0,NaN,Guatemala,NaN,14.8,10.5,1.2,2.0,7.1,45.0,30.0,15.0,66.7,27.0,NJTA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AVIBASE-B3F5E5E2,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,1.0,NHMUK,12.23.1890,F,0.0,NaN,Guatemala,NaN,13.8,9.5,1.0,1.5,8.0,45.0,31.0,14.0,68.9,30.0,NJTA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AVIBASE-B3F5E5E2,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,1.0,NHMUK,1913.3.20.972,M,0.0,NaN,Guatemala,NaN,11.8,9.4,1.0,1.8,7.2,47.0,31.0,16.0,66.0,29.0,NJTA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AVIBASE-B3F5E5E2,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,1.0,NHMUK,87.3.22.1574,M,0.0,NaN,Guatemala,NaN,11.8,8.6,1.0,1.7,4.5,47.0,30.0,17.0,63.8,30.0,NJTA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AVIBASE-B3F5E5E2,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,1.0,NHMUK,NaN,M,0.0,NaN,NaN,NaN,12.8,NaN,1.7,1.4,4.9,51.0,NaN,NaN,NaN,31.0,GT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_bl = pd.read_csv(BASE / "core/AVONET1_BirdLife.csv", encoding="latin1")

print("Shape:", df_bl.shape , "\n")
print("Columns:", list(df_bl.columns), "\n")
df_bl.head()

Shape: (11009, 37)

Columns: ['Sequence', 'Species1', 'Family1', 'Order1', 'Avibase.ID1', 'Total.individuals', 'Female', 'Male', 'Unknown', 'Complete.measures', 'Beak.Length_Culmen', 'Beak.Length_Nares', 'Beak.Width', 'Beak.Depth', 'Tarsus.Length', 'Wing.Length', 'Kipps.Distance', 'Secondary1', 'Hand-Wing.Index', 'Tail.Length', 'Mass', 'Mass.Source', 'Mass.Refs.Other', 'Inference', 'Traits.inferred', 'Reference.species', 'Habitat', 'Habitat.Density', 'Migration', 'Trophic.Level', 'Trophic.Niche', 'Primary.Lifestyle', 'Min.Latitude', 'Max.Latitude', 'Centroid.Latitude', 'Centroid.Longitude', 'Range.Size']

   Sequence               Species1       Family1           Order1       Avibase.ID1  Total.individuals  Female  Male  Unknown  Complete.measures  Beak.Length_Culmen  Beak.Length_Nares  Beak.Width  Beak.Depth  Tarsus.Length  Wing.Length  Kipps.Distance  Secondary1  Hand-Wing.Index  Tail.Length   Mass Mass.Source Mass.Refs.Other Inference Traits.inferred Reference.species    Habitat  Habitat.Density  Migration Trophic.Level Trophic.Niche Primary.Lifestyle  Min.Latitude  Max.Latitude  Centroid.Latitude  Centroid.Longitude   Range.Size
0    3103.0  Accipiter albogularis  Accipitridae  Accipitriformes  AVIBASE-BBB59880                  5       2     0        3                  4                27.7               17.8        10.6        14.7           62.0        235.2            81.8       159.5             33.9        169.0  248.8     Dunning             NaN        NO             NaN               NaN     Forest                1        2.0     Carnivore     Vertivore       Insessorial        -11.73         -4.02              -8.15              158.49     37461.21
1    3090.0       Accipiter badius  Accipitridae  Accipitriformes  AVIBASE-1A0ECB6E                 10       4     6        0                  8                20.6               12.1         8.8        11.6           43.0        186.7            62.5       127.4             32.9        140.6  131.2     Dunning             NaN        NO             NaN               NaN  Shrubland                2        3.0     Carnivore     Vertivore       Insessorial        -29.47         46.39               8.23               44.98  22374973.00
2    3125.0      Accipiter bicolor  Accipitridae  Accipitriformes  AVIBASE-ADBE44E1                 11       4     5        2                  8                25.0               13.7         8.6        12.7           58.1        229.6            56.6       174.8             24.6        186.3  287.5     Dunning             NaN        NO             NaN               NaN   Woodland                2        2.0     Carnivore     Vertivore        Generalist        -55.72         23.73             -10.10              -59.96  14309701.27
3    3116.0   Accipiter brachyurus  Accipitridae  Accipitriformes  AVIBASE-68BF920B                  4       4     0        0                  3                22.5               14.0         8.9        11.9           61.2        202.2            64.1       138.1             31.7        140.8  142.0     Dunning             NaN        NO             NaN               NaN     Forest                1        2.0     Carnivore     Vertivore       Insessorial         -6.31         -4.08              -5.45              150.68     35580.71
4    3092.0     Accipiter brevipes  Accipitridae  Accipitriformes  AVIBASE-8492E4B7                  8       4     4        0                  4                21.1               12.1         8.7        11.1           46.4        217.6            87.8       129.9             40.2        153.5  186.5     Dunning             NaN        NO             NaN               NaN     Forest                1        3.0     Carnivore     Vertivore        Generalist         31.19         55.86              45.24               45.33   2936751.80

In [16]:
df_ebird = pd.read_excel(
    BASE / "core/AVONET2_eBird.xlsx", sheet_name=1 , header=0
)

print("Shape:", df_ebird.shape, "\n")
print("Columns:", list(df_ebird.columns), "\n")
df_ebird.head()

Shape: (10661, 31)

Columns: ['Species2', 'Family2', 'Order2', 'Avibase.ID2', 'Total.individuals', 'Female', 'Male', 'Unknown', 'Complete.measures', 'Beak.Length_Culmen', 'Beak.Length_Nares', 'Beak.Width', 'Beak.Depth', 'Tarsus.Length', 'Wing.Length', 'Kipps.Distance', 'Secondary1', 'Hand-Wing.Index', 'Tail.Length', 'Mass', 'Mass.Source', 'Mass.Refs.Other', 'Inference', 'Traits.inferred', 'Reference.species', 'Habitat', 'Habitat.Density', 'Migration', 'Trophic.Level', 'Trophic.Niche', 'Primary.Lifestyle']

                Species2       Family2           Order2       Avibase.ID2  Total.individuals  Female  Male  Unknown  Complete.measures  Beak.Length_Culmen  Beak.Length_Nares  Beak.Width  Beak.Depth  Tarsus.Length  Wing.Length  Kipps.Distance  Secondary1  Hand-Wing.Index  Tail.Length   Mass Mass.Source Mass.Refs.Other Inference Traits.inferred Reference.species    Habitat  Habitat.Density  Migration Trophic.Level Trophic.Niche Primary.Lifestyle
0  Accipiter albogularis  Accipitridae  Accipitriformes  AVIBASE-BBB59880                  5       2     0        3                  4                27.7               17.8        10.6        14.7           62.0        235.2            81.8       159.5             33.9        169.0  248.8     Dunning             NaN        NO             NaN               NaN     Forest                1        2.0     Carnivore     Vertivore       Insessorial
1       Accipiter badius  Accipitridae  Accipitriformes  AVIBASE-1A0ECB6E                 10       4     6        0                  8                20.6               12.1         8.8        11.6           43.0        186.7            62.5       127.4             32.9        140.6  131.2     Dunning             NaN        NO             NaN               NaN  Shrubland                2        3.0     Carnivore     Vertivore       Insessorial
2      Accipiter bicolor  Accipitridae  Accipitriformes  AVIBASE-ADBE44E1                 11       4     5        2                  8                25.0               13.7         8.6        12.7           58.1        229.6            56.6       174.8             24.6        186.3  287.5     Dunning             NaN        NO             NaN               NaN   Woodland                2        2.0     Carnivore     Vertivore        Generalist
3   Accipiter brachyurus  Accipitridae  Accipitriformes  AVIBASE-68BF920B                  4       4     0        0                  3                22.5               14.0         8.9        11.9           61.2        202.2            64.1       138.1             31.7        140.8  142.0     Dunning             NaN        NO             NaN               NaN     Forest                1        2.0     Carnivore     Vertivore       Insessorial
4     Accipiter brevipes  Accipitridae  Accipitriformes  AVIBASE-8492E4B7                  8       4     4        0                  4                21.1               12.1         8.7        11.1           46.4        217.6            87.8       129.9             40.2        153.5  186.5     Dunning             NaN        NO             NaN               NaN     Forest                1        3.0     Carnivore     Vertivore        Generalist

In [17]:
df_birdtree = pd.read_excel( BASE / "core/AVONET3_BirdTree.xlsx", sheet_name=1 , header=0 )

print("Shape:", df_birdtree.shape, "\n")
print("Columns:", list(df_birdtree.columns), "\n")
df_birdtree.head()

Shape: (9993, 36)

Columns: ['Species3', 'Family3', 'Order3', 'Total.individuals', 'Female', 'Male', 'Unknown', 'Complete.measures', 'Beak.Length_Culmen', 'Beak.Length_Nares', 'Beak.Width', 'Beak.Depth', 'Tarsus.Length', 'Wing.Length', 'Kipps.Distance', 'Secondary1', 'Hand-Wing.Index', 'Tail.Length', 'Mass', 'Mass.Source', 'Mass.Refs.Other', 'Inference', 'Traits.inferred', 'Reference.species', 'Habitat', 'Habitat.Density', 'Migration', 'Trophic.Level', 'Trophic.Niche', 'Primary.Lifestyle', 'Min.Latitude', 'Max.Latitude', 'Centroid.Latitude', 'Centroid.Longitude', 'Range.Size', 'Species.Status']

                Species3       Family3           Order3  Total.individuals  Female  Male  Unknown  Complete.measures  Beak.Length_Culmen  Beak.Length_Nares  Beak.Width  Beak.Depth  Tarsus.Length  Wing.Length  Kipps.Distance  Secondary1  Hand-Wing.Index  Tail.Length    Mass Mass.Source Mass.Refs.Other Inference Traits.inferred Reference.species    Habitat  Habitat.Density  Migration Trophic.Level Trophic.Niche Primary.Lifestyle  Min.Latitude  Max.Latitude  Centroid.Latitude  Centroid.Longitude   Range.Size Species.Status
0  Accipiter albogularis  Accipitridae  Accipitriformes                  5       2     0        3                  4                27.7               17.8        10.6        14.7           62.0        235.2            81.8       159.5             33.9        169.0  248.75     Dunning             NaN        NO             NaN               NaN     Forest              1.0        2.0     Carnivore     Vertivore       Insessorial        -11.73         -4.02              -8.15          158.493765     37461.21         Extant
1       Accipiter badius  Accipitridae  Accipitriformes                 10       4     6        0                  8                20.6               12.1         8.8        11.6           43.0        186.7            62.5       127.4             32.9        140.6  131.15     Dunning             NaN        NO             NaN               NaN  Shrubland              2.0        3.0     Carnivore     Vertivore       Insessorial        -29.47         46.39               8.23           44.982464  22374973.00         Extant
2      Accipiter bicolor  Accipitridae  Accipitriformes                  6       2     2        2                  4                26.5               14.8         9.2        13.5           57.5        231.8            46.4       189.6             19.8        188.4  287.54     Dunning             NaN        NO             NaN               NaN   Woodland              2.0        2.0     Carnivore     Vertivore        Generalist           NaN           NaN                NaN                 NaN          NaN         Extant
3   Accipiter brachyurus  Accipitridae  Accipitriformes                  4       4     0        0                  3                22.5               14.0         8.9        11.9           61.2        202.2            64.1       138.1             31.7        140.8  142.00     Dunning             NaN        NO             NaN               NaN     Forest              1.0        2.0     Carnivore     Vertivore       Insessorial         -6.31         -4.08              -5.45          150.681314     35580.71         Extant
4     Accipiter brevipes  Accipitridae  Accipitriformes                  8       4     4        0                  4                21.1               12.1         8.7        11.1           46.4        217.6            87.8       129.9             40.2        153.5  186.48     Dunning             NaN        NO             NaN               NaN     Forest              1.0        3.0     Carnivore     Vertivore        Generalist         31.19         55.86              45.24           45.327340   2936751.80         Extant

In [18]:
df_cross = pd.read_csv( BASE / "metadata/BirdLife_BirdTree_Taxonomy_Relation.csv", encoding="latin1" )

print("Shape:", df_cross.shape , "\n")
print("Columns:", list(df_cross.columns), "\n")
df_cross.head()

Shape: (11291, 4)

Columns: ['Species1', 'Species3', 'Match.type', 'Match.notes']

                   Species1                  Species3  Match.type Match.notes
0         Abeillia abeillei         Abeillia abeillei  1BL to 1BT         NaN
1    Abroscopus albogularis    Abroscopus albogularis  1BL to 1BT         NaN
2    Abroscopus schisticeps    Abroscopus schisticeps  1BL to 1BT         NaN
3  Abroscopus superciliaris  Abroscopus superciliaris  1BL to 1BT         NaN
4            Aburria aburri            Aburria aburri  1BL to 1BT         NaN

In [19]:
df_family = pd.read_csv( BASE / "metadata/Family_Specimen_Stats.csv",encoding="latin1" )

print("Shape:", df_family.shape, "\n")
print("Columns:", list(df_family.columns), "\n")
df_family.head()

Shape: (243, 10)

Columns: ['Unnamed: 0', 'familyIDS', 'Number_of_species_per_family', 'Average_number_of_specimens_per_family', 'Average_number_of_complete_specimens_per_family', 'Portion_of_family_with_at_least_one_full_specimen', 'Portion_of_complete_specimens_per_family', 'Portion_of_family_with_at_least_four_specimens', 'Portion_of_family_with_at_least_four_full_traits_measured_per_species', 'Portion_of_family_with_at_least_four_main_traits_measured_per_species']

   Unnamed: 0      familyIDS  Number_of_species_per_family  Average_number_of_specimens_per_family  Average_number_of_complete_specimens_per_family  Portion_of_family_with_at_least_one_full_specimen  Portion_of_complete_specimens_per_family  Portion_of_family_with_at_least_four_specimens  Portion_of_family_with_at_least_four_full_traits_measured_per_species  Portion_of_family_with_at_least_four_main_traits_measured_per_species
0           1    Trochilidae                           366                                     8.8                                              4.4                                               98.9                                      68.6                                            94.8                                                                   85.2                                                                   86.1
1           2  Scotocercidae                            37                                     6.6                                              4.2                                               94.6                                      77.6                                            81.1                                                                   75.7                                                                   81.1
2           3       Cracidae                            56                                     6.3                                              3.8                                               98.2                                      69.8                                            92.9                                                                   83.9                                                                   87.5
3           4   Meliphagidae                           195                                     9.9                                              3.6                                               92.3                                      49.5                                            84.6                                                                   80.0                                                                   82.6
4           5     Thraupidae                           408                                    12.2                                              4.6                                               93.1                                      61.1                                            90.2                                                                   84.1                                                                   85.3

In [20]:
df_source = pd.read_csv( BASE / "metadata/Source_Details.csv", encoding="latin1" )

print("Shape:", df_source.shape, "\n")
print("Columns:", list(df_source.columns), "\n")
df_source.head()

Shape: (83, 8)

Columns: ['Source', 'Institution.name', 'Specimens.sampled', 'Institution.city', 'Institution.country', 'Latitude', 'Longitude', 'Address']

  Source                                      Institution.name  Specimens.sampled Institution.city Institution.country   Latitude  Longitude                                                               Address
0  NHMUK                                Natural History Museum            46060.0           London                  UK  51.496715  -0.176367                           Cromwell Rd, Kensington, London SW7 5BD, UK
1   AMNH                    American Museum of Natural History             5769.0         New York                 USA  40.782045 -73.971711                  Central Park West & 79th St, New York, NY 10024, USA
2   ZFMK        Zoologisches Forschungsmuseum Alexander Koenig             3451.0             Bonn             Germany  50.722133   7.113566                                Adenauerallee 160, 53113 Bonn, Germany
3  LSUMZ  Louisiana State University Museum of Natural Science             2494.0      Baton Rouge                 USA  30.415382 -91.180120   Murphy J. Foster Hall, 119 Dalrymple Dr, Baton Rouge, LA 70802, USA
4   FMNH                       Field Museum of Natural History             2299.0          Chicago                 USA  41.866261 -87.616981                          1400 S Lake Shore Dr, Chicago, IL 60605, USA

In [21]:
df_history = pd.read_csv( BASE / "metadata/Trait_Database_History.csv", encoding="latin1" )

print("Shape:", df_history.shape, "\n")
print("Columns:", list(df_history.columns), "\n")
df_history.head()

Shape: (21, 6)

Columns: ['Year', 'Reference', 'openSource', 'NumSpecies', 'NumSpecimen', 'NumMorphTraits']

   Year                               Reference  openSource  NumSpecies  NumSpecimen  NumMorphTraits
0  1961      Hartman 1961 Smithsonian Misc Coll           1         360         2160               4
1  1977                    Ricklefs 1977 Condor           0          82          460               8
2  1982             James 1982 Ann Zool Fennici           0         680         1360               8
3  1987  Miles, Ricklefs and Travis 1987 Am Nat           0          38          190               8
4  1991            Leisler & Winkler 1991 J Orn           0          47         1000              25